In [17]:
import pandas as pd 
import numpy as np 
import warnings
warnings.filterwarnings('ignore')

In [18]:
voyage_lists = pd.read_csv('./data/cleaned_data/voyage_schedule.csv')
applications = pd.read_csv('./data/cleaned_data/applications.csv')
completions = pd.read_csv('./data//cleaned_data/completions.csv')
transactions = pd.read_csv('./data/cleaned_data/transactions.csv')

In [20]:
# Extract list of unique voyages from schedules
voyage_list = voyage_lists["Name"].dropna().unique()

# Merge data on Unique ID
merged_df = applications.merge(transactions, on="Unique ID", how="left", suffixes=('_applications' , '_transactions'))
print(merged_df['Payee Name'].unique())
merged_df = merged_df.merge(completions, on="Unique ID", how="left", suffixes=('' , '_completion'))

# Create voyage participation columns
for voyage in voyage_list:
    merged_df[voyage] = (merged_df["What is your Voyage?"] == voyage).astype(int)

# Drop redundant voyage column
merged_df.drop(columns=["What is your Voyage?"], inplace=True)

merged_df.to_csv('./data/cleaned_data/chingu_merged_df.csv', index = False)

[nan 'Unknown' 'The Job Hackers. Fee waived'
 'Paid using email address:\ntigerjump1127@gmail.com '
 'Paid using email address: prakashdas18@gmail.com'
 'Gifted by petrecirceagwork@gmail.com\n' 'Donation' 'State of Delaware'
 'Spreadshop Sales' 'Spreadshop sales' 'U.S. Federal Income Tax Refund']

In [11]:
merged_df.head()

,Unique ID,Timestamp,Subscription Status_applications,Subscription Status DT,Voyage Role,Gender,Country Code,Goal,Goal-Other,Source,...,V18,V17,V16,V15,V14,V13,V12,V11,V10,V9
0,edbd20e5cbfe46c42e2b3c0c4bbd9863,2025-03-04 08:20:00,Active,2025-03-04,Developer,MALE,GB,GAIN EXPERIENCE,NaN,The Job Hackers,...,0,0,0,0,0,0,0,0,0,0
1,00a20162d549500bfb62ae7ee7099632,2025-03-04 06:49:00,Active,2025-03-04,Developer,FEMALE,US,NETWORK WITH SHARED GOALS,NaN,GOOGLE SEARCH,...,0,0,0,0,0,0,0,0,0,0
2,06dfc0beadcd7219bfe5eb6c430cc60e,2025-03-03 14:40:00,Active,2025-03-03,Data Scientist,NON-BINARY,US,NETWORK WITH SHARED GOALS,NaN,OTHER,...,0,0,0,0,0,0,0,0,0,0
3,200ed25bf12326664dcd1c6f0109eb3a,2025-03-03 10:52:00,Active,2025-03-03,Developer,MALE,IN,ACCELERATE LEARNING,NaN,OTHER,...,0,0,0,0,0,0,0,0,0,0
4,5e67d3c45d73517954b08441a109f6fc,2025-03-02 11:56:00,Active,2025-03-02,Developer,FEMALE,US,ACCELERATE LEARNING,NaN,PERSONAL NETWORK,...,0,0,0,0,0,0,0,0,0,0

In [12]:
merged_df.describe()

,Application Age in Days,Day-of-Week No,No. Voyages Started,Application Year,Credits Purchased,"On a scale of 0-10, how likely are you to recommend Chingu to a friend or colleagues?",V999,V55,V54,V53,...,V18,V17,V16,V15,V14,V13,V12,V11,V10,V9
count,11741.000000,11741.000000,11827.000000,11740.000000,2083.0,3523.000000,11839.0,11839.0,11839.0,11839.000000,...,11839.000000,11839.000000,11839.000000,11839.000000,11839.000000,11839.000000,11839.0,11839.0,11839.0,11839.0
mean,696.034495,4.072396,1.573011,2022.728450,0.0,9.368152,0.0,0.0,0.0,0.021792,...,0.000422,0.000591,0.000507,0.000169,0.001183,0.000507,0.0,0.0,0.0,0.0
std,416.140221,18.726732,3.250073,1.190598,0.0,1.257291,0.0,0.0,0.0,0.146011,...,0.020547,0.024310,0.022507,0.012997,0.034369,0.022507,0.0,0.0,0.0,0.0
min,0.000000,1.000000,0.000000,2019.000000,0.0,2.000000,0.0,0.0,0.0,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0
25%,391.000000,2.000000,0.000000,2022.000000,0.0,9.000000,0.0,0.0,0.0,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0
50%,656.000000,4.000000,0.000000,2023.000000,0.0,10.000000,0.0,0.0,0.0,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0
75%,934.000000,5.000000,2.000000,2024.000000,0.0,10.000000,0.0,0.0,0.0,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0
max,1975.000000,2023.000000,16.000000,2025.000000,0.0,10.000000,0.0,0.0,0.0,1.000000,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,0.0,0.0,0.0,0.0

In [7]:
merged_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11839 entries, 0 to 11838
Data columns (total 90 columns):
 #   Column                                                                                      Non-Null Count  Dtype
---  ------                                                                                      --------------  -----
 0   Unique ID                                                                                   11839 non-null  object
 1   Timestamp                                                                                   11733 non-null  object
 2   Subscription Status_applications                                                            11784 non-null  object
 3   Subscription Status DT                                                                      11717 non-null  object
 4   Voyage Role                                                                                 11839 non-null  object
 5   Gender                                                                                      11839 non-null  object
 6   Country Code                                                                                11766 non-null  object
 7   Goal                                                                                        11478 non-null  object
 8   Goal-Other                                                                                  1467 non-null   object
 9   Source                                                                                      11521 non-null  object
 10  Source-Other                                                                                4127 non-null   object
 11  Most Excited About                                                                          11014 non-null  object
 12  Country name (from Country)                                                                 10994 non-null  object
 13  Voyage (from Voyage Signups)                                                                4667 non-null   object
 14  Application Age in Days                                                                     11741 non-null  float64
 15  Application Day-of-Week                                                                     11828 non-null  object
 16  Day-of-Week No                                                                              11741 non-null  float64
 17  No. Voyages Started                                                                         11827 non-null  float64
 18  Application Date                                                                            11740 non-null  object
 19  Application Year                                                                            11740 non-null  float64
 20  Transaction Date                                                                            2075 non-null   object
 21  Subscription Status_transactions                                                            2083 non-null   object
 22  Payee Name                                                                                  2083 non-null   object
 23  Payment Source                                                                              2083 non-null   object
 24  Product                                                                                     2074 non-null   object
 25  Certificate Voyage                                                                          2083 non-null   object
 26  Payment Amount                                                                              2083 non-null   object
 27  Transaction Fee                                                                             2083 non-null   object
 28  Net Payment                                                                                 2083 non-null   object
 29  Refund Amount                                                                               2083 non-null   object
 30  Credits Purchased                                                                           2083 non-null   float64
 31  Timestamp_completion                                                                        4048 non-null   object
 32  Completed Voyage?                                                                           3993 non-null   object
 33  Completion Status                                                                           3655 non-null   object
 34  Certificate Issue Date                                                                      2278 non-null   object
 35  What is your Tier?                                                                          4246 non-null   object
 36  What is the name of the project? (If there isn't a name you can just write "no name")       3627 non-null   object
 37  What tech-stack did you use for your project? (ex. React, webpack, node.js, MongoDB, etc.)  3607 non-null   object
 38  On a scale of 0-10, how likely are you to recommend Chingu to a friend or colleagues?       3523 non-null   float64
 39  Status (from Voyage Signups Link)                                                           4088 non-null   object
 40  Role (from Voyage Signups Link)                                                             4088 non-null   object
 41  Product_completion                                                                          953 non-null    object
 42  V999                                                                                        11839 non-null  int64
 43  V55                                                                                         11839 non-null  int64
 44  V54                                                                                         11839 non-null  int64
 45  V53                                                                                         11839 non-null  int64
 46  V52                                                                                         11839 non-null  int64
 47  V51                                                                                         11839 non-null  int64
 48  V50                                                                                         11839 non-null  int64
 49  V49                                                                                         11839 non-null  int64
 50  V48                                                                                         11839 non-null  int64
 51  V47                                                                                         11839 non-null  int64
 52  V46                                                                                         11839 non-null  int64
 53  V45                                                                                         11839 non-null  int64
 54  V44                                                                                         11839 non-null  int64
 55  V43                                                                                         11839 non-null  int64
 56  V42                                                                                         11839 non-null  int64
 57  V41                                                                                         11839 non-null  int64
 58  V40                                                                                         11839 non-null  int64
 59  V39                                                                                         11839 non-null  int64
 60  V38                                                                                         11839 non-null  int64
 61  V37                                                                                         11839 non-null  int64
 62  V36                                                                                         11839 non-null  int64
 63  V35                                                                                         11839 non-null  int64
 64  V34                                                                                         11839 non-null  int64
 65  V33                                                                                         11839 non-null  int64
 66  V32                                                                                         11839 non-null  int64
 67  V31                                                                                         11839 non-null  int64
 68  V30                                                                                         11839 non-null  int64
 69  V29                                                                                         11839 non-null  int64
 70  V28                                                                                         11839 non-null  int64
 71  V27                                                                                         11839 non-null  int64
 72  V26                                                                                         11839 non-null  int64
 73  V25                                                                                         11839 non-null  int64
 74  V24                                                                                         11839 non-null  int64
 75  V23                                                                                         11839 non-null  int64
 76  V22                                                                                         11839 non-null  int64
 77  V21                                                                                         11839 non-null  int64
 78  V20                                                                                         11839 non-null  int64
 79  V19                                                                                         11839 non-null  int64
 80  V18                                                                                         11839 non-null  int64
 81  V17                                                                                         11839 non-null  int64
 82  V16                                                                                         11839 non-null  int64
 83  V15                                                                                         11839 non-null  int64
 84  V14                                                                                         11839 non-null  int64
 85  V13                                                                                         11839 non-null  int64
 86  V12                                                                                         11839 non-null  int64
 87  V11                                                                                         11839 non-null  int64
 88  V10                                                                                         11839 non-null  int64
 89  V9                                                                                          11839 non-null  int64
dtypes: float64(6), int64(48), object(36)
memory usage: 8.1+ MB

In [13]:
merged_df['Payee Name'].unique()

array([nan, 'Unknown', 'The Job Hackers. Fee waived',
       'Paid using email address:\ntigerjump1127@gmail.com ',
       'Paid using email address: prakashdas18@gmail.com',
       'Gifted by petrecirceagwork@gmail.com\n', 'Donation',
       'State of Delaware', 'Spreadshop Sales', 'Spreadshop sales',
       'U.S. Federal Income Tax Refund'], dtype=object)